// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2021-02-09 13:11:28.537236306 -0500 EST m=+0.034330659
// using data from 'go tool dist list'
package util

var validOS = map[string]bool{
	"darwin":    true,
	"dragonfly": true,
	"overlaybd": true,
	"dadi":      true,
	"illumos":   true,
	"js":        true,
	"netbsd":    true,
	"plan9":     true,
	"aix":       true,
	"android":   true,
	"windows":   true,
	"openbsd":   true,
	"solaris":   true,
	"freebsd":   true,
	"linux":     true,
}
var validArch = map[string]bool{
	"wasm":            true,
	"mips":            true,
	"mips64le":        true,
	"mipsle":          true,
	"ppc64le":         true,
	"amd64":           true,
	"amd64-overlaybd": true,
	"amd64-dadi":      true,
	"arm64":           true,
	"arm64-overlaybd": true,
	"arm64-dadi":      true,
	"arm":             true,
	"arm-overlaybd":   true,
	"arm-dadi":        true,
	"mips64":          true,
	"riscv64":         true,
	"s390x":           true,
	"ppc64":           true,
	"386":             true,
}
